# Generated by Django 6.0.6 on 2026-06-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='agency_office_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='languages_spoken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='license_state_region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='preferred_lead_routing',
            field=models.CharField(blank=True, choices=[('BOTH', 'Both'), ('BUYER', 'Buyer'), ('SELLER', 'Seller')], max_length=20),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='service_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
