# Generated by Django 6.0.6 on 2026-06-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_agentprofile_agency_office_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='languages_spoken',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='service_areas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='specialties',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
