# Generated by Django 6.0.6 on 2026-06-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_agentprofile_languages_spoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='languages_spoken',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='service_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='specialties',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
