# Generated by Django 6.0.6 on 2026-06-08 22:29

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Categories', max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('property_address', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Write a comprehensive, long detailed note about the property features, neighborhood, topography, etc.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PENDING', 'Pending'), ('UNDER_OFFER', 'Under Offer'), ('SOLD', 'Sold')], default='AVAILABLE', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_survey', models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not Available')], default='NOT_AVAILABLE', max_length=20)),
                ('deed_of_assignment', models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not Available')], default='NOT_AVAILABLE', max_length=20)),
                ('building_plan_approval', models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not Available')], default='NOT_AVAILABLE', max_length=20)),
                ('c_of_o', models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not Available')], default='NOT_AVAILABLE', max_length=20, verbose_name='C of O')),
                ('governors_consent', models.CharField(choices=[('AVAILABLE', 'Available'), ('NOT_AVAILABLE', 'Not Available')], default='NOT_AVAILABLE', max_length=20, verbose_name="Governor's Consent")),
                ('land_size', models.CharField(blank=True, help_text="e.g., '600 sqm' or '2 Plots'", max_length=100)),
                ('sq_meters', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric square meters', max_digits=10, null=True)),
                ('unit_size', models.CharField(blank=True, help_text='Built-up area (leave blank for land)', max_length=100, null=True)),
                ('construction_status', models.CharField(choices=[('BARE_LAND', 'Bare Land / Unimproved'), ('OFF_PLAN', 'Off-Plan'), ('UNDER_CONSTRUCTION', 'Under Construction'), ('COMPLETED', 'Completed')], default='COMPLETED', max_length=30)),
                ('number_of_bedrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_bathrooms', models.PositiveIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.propertycategory')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='properties.property')),
            ],
            options={
                'unique_together': {('user', 'property')},
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'category', 'price'], name='properties__status_e4c266_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['category', 'price'], name='properties__categor_018068_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=django.contrib.postgres.indexes.GinIndex(fields=['property_address'], name='property_address_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='property',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='property_title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
