# Generated by Django 6.0.6 on 2026-06-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_image_propertyimage'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='property',
            name='property_address_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='property',
            name='property_title_trgm_idx',
        ),
    ]
